IBM/restconf-driver

src/main/resources/config/application-kubernetes.yml
Reverts IBM/restconf-driver#19
=> Revert "modifying Kafka intsance name for restconf driver"

pom.xml
=> Vulnerability fix changes in RESTCONF-Driver

docs/Installation.md, src/main/resources/config/application-kubernetes.yml, src/main/resources/helm/restconf-driver/values.yaml
=> image repo changes and kafka instance changes

CONTRIBUTING.md
=> Maintainers github ID changes in contributing.MD file

src/main/resources/helm/restconf-driver/values.yaml
=> modifying icr.io path in values.yaml

pom.xml
=> upgrading tomcat version in pom.xml

src/main/java/com/ibm/restconf/config/WebSecurityConfiguration.java
=> Resricting all  /management API calls excluding /info and /health

CHANGELOG.md, pom.xml
Release activity
Signed-off-by: rkumar8j
=> Release activity

docs/Installation.md
Signed-off-by: Prasad Settipalli <prasad.settipalli@ibm.com>
Fixes 54 #4841[TNC]
=> Documentation changes for Onboarding the drivers wrt CP4NA versions for restconf-driver

src/main/java/com/ibm/restconf/service/ExternalMessagingService.java, src/main/java/com/ibm/restconf/service/LifecycleManagementService.java, src/main/java/com/ibm/restconf/service/impl/KafkaExternalMessagingServiceImpl.java, src/main/java/com/ibm/restconf/web/LifecycleController.java, src/test/java/com/ibm/restconf/service/LifecycleManagementServiceTest.java, src/test/java/com/ibm/restconf/web/LifecycleControllerTest.java
#52 
Add TenantId in Kafka message header for restconf driver
Signed-off-by: rkumar8j
=> Multitenancy changes

pom.xml
#58
SNAPSHOT version change
Signed-off-by: rkumar8j
=> SNAPSHOT version update

CONTRIBUTING.md, README.md, docs/Installation.md
#64 
Add documentation for ssl
Signed-off-by: Haynes Davis <mailto:haynes.davis@ibm.com>
=> Add documentation for ssl

CHANGELOG.md
=> release activity for version 0.1.0

pom.xml
#70
CP4NA Vulnerability : spring-security-core - CVE-2022-22978
Signed-off-by: root <root@api.ranjeet-dev.cp.fyre.ibm.com>
=> security vulnerability fix- CVE-2022-22978

CHANGELOG.md
Signed-off-by: root <root@api.ranjeet-dev.cp.fyre.ibm.com>
=> Add change description in CHANGELOG

CHANGELOG.md, pom.xml
Merging develop to master branch
=> Merging develop to master branch

src/main/java/com/ibm/restconf/service/impl/KafkaExternalMessagingServiceImpl.java, src/main/java/com/ibm/restconf/web/LifecycleController.java, src/test/java/com/ibm/restconf/web/LifecycleControllerTest.java
#74
camel case change for tenantId
=> camel case change for tenantId

src/main/java/com/ibm/restconf/config/RCDriverConstants.java, src/main/java/com/ibm/restconf/service/impl/KafkaExternalMessagingServiceImpl.java, src/main/java/com/ibm/restconf/web/LifecycleController.java
#76
Maintain tenantId as constant
=> Maintain tenantId as constant

src/main/resources/docker/Dockerfile
#78
Vulnerability fixes for restconf driver
=> Security Vulnerability Fixes

CHANGELOG.md, pom.xml
CHANGELOG file update and version change in pom.xml
Signed-off-by: rkumar8j [rkumar8j@in.ibm.com](mailto:rkumar8j@in.ibm.com)
=> Release activity for version 0.1.2

CHANGELOG.md, pom.xml, src/main/java/com/ibm/restconf/config/RCDriverConstants.java, src/main/java/com/ibm/restconf/service/impl/KafkaExternalMessagingServiceImpl.java, src/main/java/com/ibm/restconf/web/LifecycleController.java, src/main/resources/docker/Dockerfile, src/test/java/com/ibm/restconf/web/LifecycleControllerTest.java
Manual release activity- 0.1.2
=> Manual release activity- 0.1.2

src/main/resources/helm/restconf-driver/Chart.yaml
Signed-off-by: root <root@Dev-Mahesh1.fyre.ibm.com>
=> Adding appVersion in chart.yaml

CHANGELOG.md, pom.xml
release activity for cp4na-2.4.1
=> release activity for cp4na-2.4.1

src/main/resources/logback-spring.xml
#102
Fix to discard unwanted springboot security logs
=> Fix to discard unwanted springboot security logs

pom.xml
=> adding spring security in pom.xml

CHANGELOG.md, pom.xml
=> Release activity for CP4NA-2.4.2

src/main/java/com/ibm/restconf/config/BufferedRequestWrapper.java, src/main/java/com/ibm/restconf/config/RCDriverConstants.java, src/main/java/com/ibm/restconf/config/RCDriverProperties.java, src/main/java/com/ibm/restconf/config/TransactionIdFilter.java, src/main/java/com/ibm/restconf/driver/CiscoCncResponseErrorHandler.java, src/main/java/com/ibm/restconf/driver/CiscoCncServiceDriver.java, src/main/java/com/ibm/restconf/model/JWTToken.java, src/main/java/com/ibm/restconf/service/AuthService.java, src/main/java/com/ibm/restconf/service/LifecycleManagementService.java, src/main/java/com/ibm/restconf/service/impl/CiscoCncAuthService.java, src/main/java/com/ibm/restconf/service/impl/JinJavaMessageConversionServiceImpl.java, src/main/java/com/ibm/restconf/service/impl/KafkaExternalMessagingServiceImpl.java, src/main/java/com/ibm/restconf/utils/RequestResponseLogUtils.java, src/main/java/com/ibm/restconf/web/LifecycleController.java, src/test/java/com/ibm/restconf/driver/CiscoCncServiceDriverTest.java, src/test/java/com/ibm/restconf/service/CiscoCncAuthServiceTest.java, src/test/java/com/ibm/restconf/service/LifecycleManagementServiceTest.java, src/test/java/com/ibm/restconf/utils/RequestResponseLogUtilsTest.java, src/test/java/com/ibm/restconf/web/LifecycleControllerTest.java
All logging related code changes and tenantId updates.
=> Release 2.5.0

pom.xml
=> updated spring boot to fix vulnerability

developer_docs/release.md
=> updated release.md to use prod profile

src/main/java/com/ibm/restconf/common/security/PasswordMasker.java, src/main/resources/logback-spring.xml
=> Added masking for the password in the Execution request's deployment 

pom.xml
1. Updated spring boot to 2.7.10
2. updated snakeyml version 2.0
=> fixed vulnerabilities

CHANGELOG.md, pom.xml, src/main/java/com/ibm/restconf/driver/CiscoCncServiceDriver.java
Merge develop->master for release 0.2.1-RC1
=> Merge develop->master for release 0.2.1-RC1

CHANGELOG.md, pom.xml
Merge develop to master for pre-release of 0.2.2-RC1
=> Merge develop to master for pre-release of 0.2.2-RC1

pom.xml
merge develop to master to release v0.2.2
=> merge develop to master to release v0.2.2

CONTRIBUTING.md, developer_docs/release.md
Will merge once branch is renamed
=> Rename to main - references update

CHANGELOG.md, CONTRIBUTING.md, developer_docs/release.md, pom.xml
merge develop->main for release v0.2.3
=> merge develop->main for release v0.2.3

pom.xml
Update pom.xml for release v0.2.3
=> Update pom.xml for release v0.2.3

pom.xml, src/main/java/com/ibm/restconf/config/BufferedRequestWrapper.java, src/main/java/com/ibm/restconf/config/TransactionIdFilter.java, src/main/java/com/ibm/restconf/config/WebSecurityConfiguration.java, src/main/java/com/ibm/restconf/driver/CiscoCncServiceDriver.java, src/main/java/com/ibm/restconf/security/CookieAuthenticatedRestTemplate.java, src/main/java/com/ibm/restconf/service/impl/KafkaExternalMessagingServiceImpl.java, src/main/java/com/ibm/restconf/utils/LoggingUtils.java, src/main/java/com/ibm/restconf/web/LifecycleController.java, src/main/java/com/ibm/restconf/web/RestConfExceptionHandlingControllerAdvice.java, src/main/resources/config/application.yml, src/test/java/com/ibm/restconf/web/LifecycleControllerTest.java
1. Updated pom.xml to use Spring boot 3.0.0. 
2. Replaced old `javax` packaging name to `jakarta`
3. Removed deprecated functions and updated with new one.
=> Spring Boot 3.0 upgrade and dependency update-Issue/138

pom.xml
Fix for https://github.com/IBM/restconf-driver/issues/143
=> Fix for vulnerabilities

CHANGELOG.md, pom.xml
Merge develop->main brach for release 0.3.1
=> Merge develop->main brach for release 0.3.1
